/**
 * @sbr/panel-core — web panel server core: two-gate access control + guild-scoped
 * page-data resolvers. `apps/web-panel` serves these view models as JSON and its
 * browser client renders them; the types are shared by both halves.
 */
export {
  authorize,
  authorizeRole,
  PAGE_TIERS,
  PANEL_ACCESS_FLOOR,
  managesInDiscord,
  type PanelSession,
  type PanelPage,
  type AccessDecision,
  type DenyReason,
  type RoleResolver,
} from "./access.js";
export {
  PanelService,
  STALE_AFTER_MS,
  EXPECTED_SERVICES,
  HEARTBEAT_STALE_MS,
  type ServiceHealthVM,
  type ServiceInstanceVM,
  type PanelServiceDeps,
  type PageResult,
  type OverviewVM,
  type ModerationVM,
  type RelayVM,
  type ModerationActionVM,
  type SelectorVM,
  type AnalyticsVM,
  type EventsVM,
  type EventMetricStandings,
  type EventStanding,
  type EventAttendance,
  type EventAttendee,
  type EventRsvp,
  type MembersVM,
  DIRECTORY_PAGE_SIZE,
  DIRECTORY_SIDES,
  isDirectorySide,
  type SettingsVM,
  type XpVM,
  type MilestonesVM,
  type LeaderboardVM,
  type LeaderboardBoardVM,
  type LeaderboardTabVM,
  type RolesVM,
  type RolesHealthVM,
  type TicketsVM,
  type WordlistVM,
} from "./service.js";
// Re-exported so the panel's browser half, which has no bundler and cannot
// import @sbr/moderation, can still type the pack catalogue it is handed.
export type { PackSelection, WordlistPack } from "@sbr/moderation";
export {
  XP_SOURCE_ORDER,
  type HealthVM,
  type PermissionsVM,
  type PermissionCapabilityVM,
  type PermissionCommandVM,
} from "./service.js";
export type {
  DirectoryKind,
  DirectorySource,
  DirectoryVM,
  DirectoryChannel,
  DirectoryRole,
  DirectoryMember,
} from "./directory.js";
export {
  PanelMutations,
  MUTATION_TIERS,
  MUTATION_NAMES,
  MUTATION_COOLDOWN_MS,
  type MutationName,
  type MutationResult,
  type MutationError,
  type MutationErrorKind,
  type MutationLimiter,
  type JobTrigger,
  type TicketEffects,
  type EventEffects,
  type RoleMenuEffects,
  MANUAL_JOB_COOLDOWN_MS,
  type PanelMutationsDeps,
  type ConfigAuditEntry,
  type ConfigAuditSink,
} from "./mutations.js";
export {
  bucketRange,
  dimValue,
  shapeAnalytics,
  MAX_BUCKETS,
  type ChartSeries,
  type MetricChart,
  type ShapeOptions,
} from "./series.js";
export { noPanelCache, PANEL_CACHE_TTL, type PanelCache } from "./cache.js";
export { commandStatsToCsv, csvCell, rollupsToCsv, toCsv } from "./csv.js";
export type {
  PanelReads,
  GuildCard,
  OverviewCounts,
  MembershipStats,
  ActivityKind,
  ActivityEntry,
  JoinAttempt,
  LinkedMember,
  DirectoryMemberRow,
  DirectorySide,
  DirectoryQuery,
  DirectoryPage,
  RollupPoint,
  RollupPeriod,
  CommandUsageStat,
  PanelEvent,
  EventStandingRow,
  JobHealth,
  HeartbeatReader,
  ServiceHeartbeat,
  RelayCommandRecord,
  RelayLogReader,
  PermSubjectKind,
  PermissionException,
  PermissionExceptionStore,
  CommandCatalog,
  CommandCatalogEntry,
  RoleRefusalVM,
  RolesInsight,
} from "./reads.js";
export { ROLE_PREVIEW_LIMIT } from "./reads.js";
