/**
 * @sbr/panel-core — web panel server core: two-gate access control + guild-scoped
 * page-data resolvers. `apps/web-panel` serves these view models as JSON and its
 * browser client renders them; the types are shared by both halves.
 */
export {
  authorize,
  authorizeRole,
  PAGE_TIERS,
  type PanelSession,
  type PanelPage,
  type AccessDecision,
  type DenyReason,
  type RoleResolver,
} from "./access.js";
export {
  PanelService,
  STALE_AFTER_MS,
  EXPECTED_SERVICES,
  HEARTBEAT_STALE_MS,
  type ServiceHealthVM,
  type ServiceInstanceVM,
  type PanelServiceDeps,
  type PageResult,
  type OverviewVM,
  type ModerationVM,
  type ModerationActionVM,
  type SelectorVM,
  type AnalyticsVM,
  type EventsVM,
  type EventAttendance,
  type EventRsvp,
  type MembersVM,
  DIRECTORY_PAGE_SIZE,
  DIRECTORY_SIDES,
  isDirectorySide,
  type SettingsVM,
  type XpSettingsVM,
  type MilestonesVM,
  type TicketsVM,
  type WordlistVM,
  XP_SOURCE_ORDER,
  type HealthVM,
  type PermissionsVM,
  type PermissionCapabilityVM,
  type PermissionCommandVM,
} from "./service.js";
export type {
  DirectoryKind,
  DirectorySource,
  DirectoryVM,
  DirectoryChannel,
  DirectoryRole,
  DirectoryMember,
} from "./directory.js";
export {
  PanelMutations,
  MUTATION_TIERS,
  MUTATION_NAMES,
  MUTATION_COOLDOWN_MS,
  type MutationName,
  type MutationResult,
  type MutationError,
  type MutationErrorKind,
  type MutationLimiter,
  type JobTrigger,
  MANUAL_JOB_COOLDOWN_MS,
  type PanelMutationsDeps,
  type ConfigAuditEntry,
  type ConfigAuditSink,
} from "./mutations.js";
export {
  bucketRange,
  dimValue,
  shapeAnalytics,
  MAX_BUCKETS,
  type ChartSeries,
  type MetricChart,
  type ShapeOptions,
} from "./series.js";
export { commandStatsToCsv, csvCell, rollupsToCsv, toCsv } from "./csv.js";
export type {
  PanelReads,
  GuildCard,
  OverviewCounts,
  MembershipStats,
  ActivityKind,
  ActivityEntry,
  JoinAttempt,
  LinkedMember,
  DirectoryMemberRow,
  DirectorySide,
  DirectoryQuery,
  DirectoryPage,
  RollupPoint,
  RollupPeriod,
  CommandUsageStat,
  PanelEvent,
  JobHealth,
  HeartbeatReader,
  ServiceHeartbeat,
  PermSubjectKind,
  PermissionException,
  PermissionExceptionStore,
  CommandCatalog,
  CommandCatalogEntry,
} from "./reads.js";
